[package]
name = "gf"
version = "0.1.0"
authors = ["Saulo Fonseca"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.5"
num-integer = "0.1.42"
num-traits = "0.2.11"
num = "0.2.1"
impl_ops = "0.1.1"

