[package]
name = "curve"
version = "0.1.0"
authors = ["Saulo Fonseca"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.2.5"
gf = {path = "../gf"}
point = {path = "../point"}

